// <auto-generated />
using System;
using ApiTicketRobChat.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTicketRobChat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiTicketRobChat.Models.TicketsRobChat", b =>
                {
                    b.Property<int>("fiIDTicketSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fiIDTicketSolicitud"));

                    b.Property<string>("fcApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fcComentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fcNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fcQueja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fcTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fdFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("fiIDTicketSaris")
                        .HasColumnType("int");

                    b.Property<int>("fiIDTicketTobchat")
                        .HasColumnType("int");

                    b.HasKey("fiIDTicketSolicitud");

                    b.ToTable("TicketRobChat");
                });
#pragma warning restore 612, 618
        }
    }
}
